const actions_types = {
  FETCH_COINLIST: "FETCH_COINLIST",
  FETCH_COINLIST_SUCCESS: "FETCH_COINLIST_SUCCESS",
  FETCH_COINLIST_FAILURE: "FETCH_COINLIST_FAILURE",
  FETCH_EXCHANGESLIST: "FETCH_EXCHANGESLIST",
  FETCH_EXCHANGESLIST_SUCCESS: "FETCH_EXCHANGESLIST_SUCCESS",
  FETCH_EXCHANGESLIST_FAILURE: "FETCH_EXCHANGESLIST_FAILURE",
  FETCH_COIN: "FETCH_COIN",
  FETCH_COIN_SUCCESS: "FETCH_COIN_SUCCESS",
  FETCH_COIN_FAILURE: "FETCH_COIN_FAILURE",
  FETCH_COIN_HISTORY: "FETCH_COIN_HISTORY",
  FETCH_COIN_HISTORY_SUCCESS: "FETCH_COIN_HISTORY_SUCCESS",
  FETCH_COIN_HISTORY_FAILURE: "FETCH_COIN_HISTORY_FAILURE",
  UPDATE_PRICE: "UPDATE_PRICE"
};

export default actions_types;
