const actions_types = {
  FETCH_ASSETS: "FETCH_ASSETS",
  FETCH_ASSETS_SUCCESS: "FETCH_ASSETS_SUCCESS",
  FETCH_ASSETS_FAILURE: "FETCH_ASSETS_FAILURE",
  FETCH_EXCHANGES: "FETCH_EXCHANGES",
  FETCH_EXCHANGES_SUCCESS: "FETCH_EXCHANGES_SUCCESS",
  FETCH_EXCHANGES_FAILURE: "FETCH_EXCHANGES_FAILURE"
};

export default actions_types;
