const actions_types = {
  FETCH_COINLIST: "FETCH_COINLIST",
  FETCH_COINLIST_SUCCESS: "FETCH_COINLIST_SUCCESS",
  FETCH_COINLIST_FAILURE: "FETCH_COINLIST_FAILURE",
  FETCH_EXCHANGESLIST: "FETCH_EXCHANGESLIST",
  FETCH_EXCHANGESLIST_SUCCESS: "FETCH_EXCHANGESLIST_SUCCESS",
  FETCH_EXCHANGESLIST_FAILURE: "FETCH_EXCHANGESLIST_FAILURE"
};

export default actions_types;
